# Generated by Django 2.2.1 on 2019-05-17 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='temparature',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='sensor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 11, 34, 42, 217328)),
        ),
    ]
