# Generated by Django 2.2.1 on 2019-05-20 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190517_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='umidity',
        ),
        migrations.CreateModel(
            name='SensorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umidity', models.PositiveIntegerField()),
                ('temperature', models.IntegerField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 5, 20, 22, 52, 13, 800613))),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensors.Sensor')),
            ],
        ),
    ]
