# Generated by Django 2.2.1 on 2019-05-20 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190520_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorline',
            old_name='umidity',
            new_name='humidity',
        ),
        migrations.AlterField(
            model_name='sensorline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 20, 22, 53, 15, 141311)),
        ),
    ]
