# Generated by Django 2.2.1 on 2019-05-23 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20190523_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 22, 35, 10, 905513)),
        ),
    ]
