# Generated by Django 2.2.1 on 2019-05-25 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20190523_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='max_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 0, 1, 37, 364162)),
        ),
    ]
