# Generated by Django 2.2.1 on 2019-05-25 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_auto_20190525_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='max_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='min_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sensorline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 0, 12, 37, 458447)),
        ),
    ]
